version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_DATABASE: vanguarda_db
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"